### PR TITLE
fix/navbar-and-hero, navbar postion fixed, hero padded

### PR DESCRIPTION
**Pull request by RB-Isiaq**
Based on the designer's review.

I gave the Navbar a fixed position and updated the padding of the hero component

### CODE REVIEW

**Comment by edustipend-root** [comment]
> Based on the designer's review.
> 
> I gave the Navbar a fixed position and updated the padding of the hero component

Hello @RB-Isiaq, here is what the screen looks like on mobile after your change. Can you look at this?

image

**Review by edustipend-root — CHANGES_REQUESTED** [review]
Please refer to comment

**Comment by RB-Isiaq** [comment]
> > Based on the designer's review.
> > I gave the Navbar a fixed position and updated the padding of the hero component
> 
> Hello @RB-Isiaq, here is what the screen looks like on mobile after your change. Can you look at this?
> 
> image

I was thinking of not touching the landing and ambassador pages styles before, but I did now. Please review. Thanks

**Comment by RB-Isiaq** [comment]
I think I'll have to do some updates again after checking it live, I'll let you know when I do that.

**Comment by RB-Isiaq** [comment]
We're good to go, you can please review and merge @edustipend-root

**Pull request merged**
