### PR TITLE
Feat/donation quotation

### PR DESCRIPTION
**Pull request by Ezeh20**
This PR holds the donation quotation feedback 

https://github.com/edustipend/dotorg/assets/29344226/b68a4106-49de-4ea1-86ac-b8fd1c83c17a

### CODE REVIEW

**Comment by edustipend-root** [comment]
@Ezeh20, thanks so much for working on this. It looks good for the most part but I have couple of comments:

- First, I don't think I would want us to have the `Thank you for the donation` message show up for amounts between N1,000 and N10,000, it can be confusing to users when they have not made a donation. Instead, let's just say `This amount will help us empower a learner` and then from N10,000** and then we start showing them text.

- Let's change the text we show to not show the number of stipend. So instead of saying `'N15,000 can cover 1 data subscription for 1 learner'`, let's say `'N15,000 can help get data subscription for 1 learner'`.  Similarly, for the course stipend, let's change the text to `'N25,000 can help pay for online courses for 1 learner'` instead of saying `'N25,000 can cover 1 course enrolment for 1 learner'` - so we only talk about the stipend and the number of learners impacted, not the number of stipend. Let me know if that makes sense.

- Also, when the number of learners becomes more than 1, let's add `'about'` as a prefix. So for example, instead of saying `'N25,000 can cover 2 data subscription for 2 learners'`, let's say `'N25,000 can help get data subscription for about 2 learners'`.


image


- Finally, I don't think I'm very comfortable with how we are showing two lines of text as shown in the image above when we get to higher amounts, it can be a bit confusing to the users. For example are we saying that _N29,000 can get data subscription for about 2 learners **AND** course enrolment for 1 learner_? So what I would prefer is that when the users scrolls to amounts that have impact on more than one stipend category, the text should read something like `'N29,000 can help get data subscription for about 2 learners OR help pay for online courses for 1 learner'` (see the OR I added)

image

So when the user scrolls to a laptop amount like above for example, the text should read:

```
N410,000 can help get a laptop for 1 learner OR 
N410,000 can help pay for online courses for about 16 learners OR 
N410,000 can help get data subscription for about 41 learners
```

Note that **OR** word should come at the end of each line and that the order of displaying the stipend categories is laptop stipend comes first >> then online courses >> then data subscription.

Please read through and let me know if this makes sense to you @Ezeh20 and reach out if you have any questions or comments.

**Review by edustipend-root — APPROVED** [review]
@Ezeh20, thanks so much for this great work, I've added a comment [here](https://github.com/edustipend/dotorg/pull/173#issuecomment-2172908655), please read through and lmk if you have any questions.

Let's make the changes and I can approve and merge this PR.

**Review by edustipend-root — CHANGES_REQUESTED** [review]
@Ezeh20, thanks so much for this great work, I've added a comment [here](https://github.com/edustipend/dotorg/pull/173#issuecomment-2172908655), please read through and lmk if you have any questions.

Let's make the changes and I can approve and merge this PR.

**Comment by Ezeh20** [comment]
> @Ezeh20, thanks so much for this great work, I've added a comment [here](https://github.com/edustipend/dotorg/pull/173#issuecomment-2172908655), please read through and lmk if you have any questions.
> 
> Let's make the changes and I can approve and merge this PR.

made the changes

**Review by edustipend-root — APPROVED** [review]
Thanks for the changes @Ezeh20!

**Pull request merged**
