### PR TITLE
Feature/quote-component

### PR DESCRIPTION
**Pull request by misspelz**
Here's the PR for the Quote component to be used in the Learner's Dashboard

### CODE REVIEW

**Review by edustipend-root — CHANGES_REQUESTED** [review]
Hello @misspelz, you opened your PR against `main` branch instead of `develop`.
Can you update the base branch?

**Comment by misspelz** [comment]
> Hello @misspelz, you opened your PR against `main` branch instead of `develop`.
> Can you update the base branch?

Oh, okay. I will do that now

**Comment by misspelz** [comment]
> Hello @misspelz, you opened your PR against `main` branch instead of `develop`. Can you update the base branch?

Done sir

**Review by edustipend-root — APPROVED** [review]
LGTM!

**Pull request merged**
